### ISSUE TITLE
can't access property "src", props.image is undefined in a Next.js app

### ISSUE THREAD

**Issue by talentlessguy** [rpearce/image-zoom#279]
This issue is a: 

- Bug report

## Expected behavior

I expected the component to work properly.

## Actual behavior

It threw an error that crashed the page:

```
TypeError: Cannot read property 'src' of undefined
    at new ImageZoom (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/react-medium-image-zoom@3.1.3_react-dom@17.0.2/node_modules/react-medium-image-zoom/lib/ImageZoom.js:59:24)
    at processChild (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/react-dom@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3305:14)
    at resolve (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/react-dom@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/react-dom@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/react-dom@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/react-dom@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/next@10.1.3_6a88c9e99d2b050334e66586ecc1f518/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (webpack-internal:///./node_modules/.pnpm/next@10.1.3_6a88c9e99d2b050334e66586ecc1f518/node_modules/next/dist/pages/_document.js:141:19)
    at loadGetInitialProps (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/next@10.1.3_6a88c9e99d2b050334e66586ecc1f518/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/next@10.1.3_6a88c9e99d2b050334e66586ecc1f518/node_modules/next/dist/next-server/server/render.js:54:1145)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/next@10.1.3_6a88c9e99d2b050334e66586ecc1f518/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/next@10.1.3_6a88c9e99d2b050334e66586ecc1f518/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async DevServer.renderToHTMLWithComponents (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/next@10.1.3_6a88c9e99d2b050334e66586ecc1f518/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (/home/v1rtl/Coding/v1rtl_site/node_modules/.pnpm/next@10.1.3_6a88c9e99d2b050334e66586ecc1f518/node_modules/next/dist/next-server/server/next-server.js:138:522)
```

## Steps to reproduce behavior

1. Create a folder with images
2. Use [next-images](https://github.com/twopluszero/next-images) plugin for loading images
3. Import the array of images
4. Try to use them inside of `<Zoom />`

## Example of behavior

here's a sample code:

```ts
import React from 'react'
import images from '../public/drawings/*.jpg'
import Zoom from 'react-medium-image-zoom'

const Images = () => {
  return (
      <div>
        {images.map((img: string, i: number) => (
          <Zoom overlayBgColorEnd="'rgba(49, 49, 49, 0.87)'" key={i}>
            <img src={img} />
          </Zoom>
        ))}
      </div>
  )
}

export default Images
```

This works thou (without wrapping into `Zoom`):

```ts
import React from 'react'
import images from '../public/drawings/*.jpg'
import Zoom from 'react-medium-image-zoom'

const Images = () => {
  return (
      <div>
        {images.map((img: string, i: number) => (
          <img src={img}  />
        ))}
      </div>
  )
}

export default Images
```

## Useful info

package.json:

```jsonc
"@emotion/react": "^11.1.5",
"next": "~10.1.3",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-medium-image-zoom": "^3.1.3"
```

**Comment by rpearce** [comment]
@talentlessguy It looks like you're using version 3, so you should take a look at the API for that: https://github.com/rpearce/image-zoom/tree/v3.x

```js
import ImageZoom from 'react-medium-image-zoom'

function MyComponent(props) {
  return (
    <div>
      <p>Some text...</p>

      <ImageZoom
        image={{
          src: 'bridge.jpg',
          alt: 'Golden Gate Bridge',
          className: 'img',
          style: { width: '50em' }
        }}
        zoomImage={{
          src: 'bridge-big.jpg',
          alt: 'Golden Gate Bridge'
        }}
      />

      <p>Some text...</p>
    </div>
  )
}
```

**Comment by talentlessguy** [comment]
@rpearce oops my bad, for some reason it installed v3 but not v4

closing

**Comment by rpearce** [comment]
@talentlessguy v3 and v4 are very different, so one may suit your needs better than the other.

Also, v5 (so to be redone) will be re-worked when I can circle back to it. https://github.com/rpearce/image-zoom/discussions/274
